### ISSUE TITLE
Pulumi fails with execption when using CreationRoleProvider in C#

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi-eks#1113]
### What happened?

When attempting to use the CreationRoleProvider, pulumi will fail with an exception.  Below is a full reproduction.

```
Do you want to perform this update? yes
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/initech/webserver-asg/dev/updates/7

     Type                 Name               Status     Info
     pulumi:pulumi:Stack  webserver-asg-dev             'dotnet build -nologo .' completed successfully
     Type                             Name                       Status                  Info
 +   pulumi:pulumi:Stack              webserver-asg-dev          **creating failed**     1 error; 127 messages
 +   ├─ aws:iam:Role                  eks-creator                created (0.94s)         
 +   │  └─ pulumi:providers:aws       cluster-creation-provider  created (0.15s)         
 +   ├─ aws:iam:Policy                eks-creator-policy         created (0.94s)         
 +   └─ aws:iam:RolePolicyAttachment  eksRolePolicyAttachment    created (0.40s)         

Policies:
    ✅ aws-iso27001-compliance-ready-policies-typescript@v0.0.1

Diagnostics:
  pulumi:pulumi:Stack (webserver-asg-dev):
    TypeError: provider.getPackage is not a function: TypeError: provider.getPackage is not a function
        at convertToProvidersMap (/snapshot/eks/node_modules/@pulumi/pulumi/resource.js:334:25)
        at new Resource (/snapshot/eks/node_modules/@pulumi/pulumi/resource.js:205:133)
        at new CustomResource (/snapshot/eks/node_modules/@pulumi/pulumi/resource.js:400:9)
        at new Cluster (/snapshot/eks/node_modules/@pulumi/aws/eks/cluster.js:200:9)
        at createCore (/snapshot/eks/bin/cluster.js:331:24)
        at createCluster (/snapshot/eks/bin/cluster.js:827:18)
        at new ClusterInternal (/snapshot/eks/bin/cluster.js:906:25)
        at Object.construct (/snapshot/eks/bin/cmd/provider/cluster.js:21:29)
        at Provider.construct (/snapshot/eks/bin/cmd/provider/index.js:131:24)
        at Server.<anonymous> (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:315:52)

    error: Running program '/Users/james/Code/aws-webserver/bin/Debug/net6.0/WebAutoscaling.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="provider.getPackage is not a function")
       at async Task<RegisterResourceResponse> Pulumi.GrpcMonitor.RegisterResourceAsync(Resource resource, RegisterResourceRequest request)
       at async Task<(string urn, string id, Struct data, ImmutableDictionary<string, ImmutableHashSet<Resource>> dependencies)> Pulumi.Deployment.RegisterResourceAsync(Resource resource, bool remote, Func<string, Resource> newDependency, ResourceArgs args, ResourceOptions options)
       at async Task<(string urn, string id, Struct data, ImmutableDictionary<string, ImmutableHashSet<Resource>> dependencies)> Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, bool remote, Func<string, Resource> newDependency, ResourceArgs args, ResourceOptions options)
       at async Task Pulumi.Deployment.CompleteResourceAsync(Resource resource, bool remote, Func<string, Resource> newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary<string, IOutputCompletionSource> completionSources)
       at async Task<T> Pulumi.Output<T>.GetValueAsync(T whenUnknown)
       at async Task<string> Pulumi.Deployment+EngineLogger.TryGetResourceUrnAsync(Resource resource)
       at async Task<OutputData<U>> Pulumi.Output<T>.ApplyHelperAsync<U>(Task<OutputData<T>> dataTask, Func<T, Output<U>> func)
       at async Task<OutputData<object>> Pulumi.Output<T>.Pulumi.IOutput.GetDataAsync()
       at async Task<object> Pulumi.Serialization.Serializer.SerializeAsync(string ctx, object prop, bool keepResources, bool keepOutputValues)
       at async Task<RawSerializationResult> Pulumi.Deployment.SerializeFilteredPropertiesRawAsync(string label, IDictionary<string, object> args, Predicate<string> acceptKey, bool keepResources, bool keepOutputValues)
       at async Task<SerializationResult> Pulumi.Deployment.SerializeFilteredPropertiesAsync(string label, IDictionary<string, object> args, Predicate<string> acceptKey, bool keepResources, bool keepOutputValues)
       at async Task<Struct> Pulumi.Deployment.SerializeAllPropertiesAsync(string label, IDictionary<string, object> args, bool keepResources, bool keepOutputValues)
       at async Task Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output<IDictionary<string, object>> outputs)
```

### Example

```c#
using System.Threading;
using Pulumi;
using Pulumi.Aws;
using Pulumi.Aws.Iam;
using Pulumi.Aws.Inputs;
using Pulumi.Eks.Inputs;
using Aws = Pulumi.Aws;
using Eks = Pulumi.Eks;

public class EksProvider : Stack
{
    [Output]
    public Output<string> kubeConfig { get; private set; }

    public EksProvider()
    {
        // Grab some values from the Pulumi configuration (or use default values)

        var eksRole = new Role("eks-creator", new RoleArgs
        {
            AssumeRolePolicy = GetCallerIdentity.Invoke().Apply(caller => @$"{{
                ""Version"": ""2012-10-17"",
                ""Statement"": [{{
                    ""Effect"": ""Allow"",
                    ""Principal"": {{
                        ""AWS"": ""arn:aws:iam::{caller.AccountId}:root""
                    }},
                    ""Action"": ""sts:AssumeRole""
                }}]
            }}"),
        });

        var eksRolePolicy = new Policy("eks-creator-policy", new PolicyArgs {
            PolicyDocument = @"{
                ""Version"": ""2012-10-17"",
                ""Statement"": [
                    {
                        ""Effect"": ""Allow"",
                        ""Action"": [
                            ""eks:*"",
                            ""iam:*"",
                            ""cloudformation:*"",
                            ""ec2:*"",
                            ""autoscaling:*"",
                            ""ssm:*"",
                            ""kms:*""
                        ],
                        ""Resource"": ""*""
                    },
                    {
                        ""Effect"": ""Allow"",
                        ""Action"": ""sts:GetCallerIdentity"",
                        ""Resource"": ""*""
                    }
                ]
            }"
        });

        // Attach the Amazon EKS service role policy to the role
        var eksRolePolicyAttachment = new RolePolicyAttachment("eksRolePolicyAttachment", new RolePolicyAttachmentArgs
        {
            Role = eksRole.Name,
            PolicyArn = eksRolePolicy.Arn
        });

        // Assume and use our creator role to create our cluster.        
        var cluster = eksRole.Arn.Apply(arn => {

            Aws.Provider p;

            if (Deployment.Instance.IsDryRun) {
                // prevent pulumi from attempting to assume non-existant provider on dry run
                p = new Aws.Provider("cluster-creation-provider");
            } else {
                Thread.Sleep(30000);
                p = new Aws.Provider($"cluster-creation-provider",
                    new Aws.ProviderArgs
                    {
                        Region = "us-west-2",
                        AssumeRole = new ProviderAssumeRoleArgs
                        {
                            RoleArn = arn
                        }
                    }, new CustomResourceOptions { Parent = eksRole });
            }

            return new Eks.Cluster("creation-provider-test", new Eks.ClusterArgs
            {
                CreationRoleProvider = new CreationRoleProviderArgs
                {
                    Role = eksRole,
                    Provider = p
                },
                CreateOidcProvider = false,
                SkipDefaultNodeGroup = true,
                NodeAssociatePublicIpAddress = false,
                EndpointPrivateAccess = true,
                EndpointPublicAccess = true,
            });
        });        

        
        kubeConfig = cluster.Apply( c => c.KubeconfigJson );  
    }
}
```

### Output of `pulumi about`

```
CLI          
Version      3.111.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.28.2
awsx        2.3.0
docker      4.5.0
dotnet      unknown
eks         2.3.0
kubernetes  4.9.1
tls         4.11.1

Host     
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='8.0.100'

Current Stack: initech/webserver-asg/dev

TYPE                                               URN
pulumi:providers:aws                               urn:pulumi:dev::webserver-asg::pulumi:providers:aws::default_6_28_2
pulumi:pulumi:Stack                                urn:pulumi:dev::webserver-asg::pulumi:pulumi:Stack::webserver-asg-dev
aws:iam/policy:Policy                              urn:pulumi:dev::webserver-asg::aws:iam/policy:Policy::eks-creator-policy
aws:iam/role:Role                                  urn:pulumi:dev::webserver-asg::aws:iam/role:Role::eks-creator
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::webserver-asg::aws:iam/rolePolicyAttachment:RolePolicyAttachment::eksRolePolicyAttachment
pulumi:providers:aws                               urn:pulumi:dev::webserver-asg::aws:iam/role:Role$pulumi:providers:aws::cluster-creation-provider
pulumi:providers:eks                               urn:pulumi:dev::webserver-asg::pulumi:providers:eks::default_2_3_0
pulumi:providers:aws                               urn:pulumi:dev::webserver-asg::pulumi:providers:aws::default_6_0_4


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/initech
User           initech
Organizations  initech
Token type     team: application
Token type     cli

Dependencies:
NAME         VERSION
Pulumi       3.60.0
Pulumi.Aws   6.28.2
Pulumi.Awsx  2.3.0
Pulumi.Eks   2.3.0
Pulumi.Tls   4.11.1

Pulumi locates its logs in /var/folders/b5/__9f51g104dbl435yq2tw8680000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by automagic** [comment]
Note this is related to https://github.com/pulumi/pulumi-eks/pull/205

**Comment by rquitales** [comment]
I can confirm that there are issues with passing in the AWS provider in C#. Porting the code example over to typescript did not result in a deployment error.

**Comment by rquitales** [comment]
After investigating further, it appears that we won't be able to currently support `CreationRoleProvider` in non-nodejs Pulumi programs. This is due to how MLC SDKs serialize the passed provider into json, not a fully initialized instance of the Provider. There isn't a way to reconstruct a provider from the serialized json either.

As a workaround, you should be able to specify these settings within `Cluster.ProviderCredentialOpts` instead, ref: https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#providercredentialopts_csharp.

An updated example would be:
```csharp
using System.Threading;
using Pulumi;
using Pulumi.Aws;
using Pulumi.Aws.Iam;
using Pulumi.Aws.Inputs;
using Pulumi.Eks.Inputs;
using Aws = Pulumi.Aws;
using Eks = Pulumi.Eks;

public class EksProvider : Stack
{
    [Output]
    public Output<string> kubeConfig { get; private set; }

    public EksProvider()
    {
        // Grab some values from the Pulumi configuration (or use default values)

        var eksRole = new Role("eks-creator", new RoleArgs
        {
            AssumeRolePolicy = GetCallerIdentity.Invoke().Apply(caller => @$"{{
                ""Version"": ""2012-10-17"",
                ""Statement"": [{{
                    ""Effect"": ""Allow"",
                    ""Principal"": {{
                        ""AWS"": ""arn:aws:iam::{caller.AccountId}:root""
                    }},
                    ""Action"": ""sts:AssumeRole""
                }}]
            }}"),
        });

        var eksRolePolicy = new Policy("eks-creator-policy", new PolicyArgs {
            PolicyDocument = @"{
                ""Version"": ""2012-10-17"",
                ""Statement"": [
                    {
                        ""Effect"": ""Allow"",
                        ""Action"": [
                            ""eks:*"",
                            ""iam:*"",
                            ""cloudformation:*"",
                            ""ec2:*"",
                            ""autoscaling:*"",
                            ""ssm:*"",
                            ""kms:*""
                        ],
                        ""Resource"": ""*""
                    },
                    {
                        ""Effect"": ""Allow"",
                        ""Action"": ""sts:GetCallerIdentity"",
                        ""Resource"": ""*""
                    }
                ]
            }"
        });

        // Attach the Amazon EKS service role policy to the role
        var eksRolePolicyAttachment = new RolePolicyAttachment("eksRolePolicyAttachment", new RolePolicyAttachmentArgs
        {
            Role = eksRole.Name,
            PolicyArn = eksRolePolicy.Arn
        });

        // Assume and use our creator role to create our cluster.        
        var cluster = eksRole.Arn.Apply(arn => {

            return new Eks.Cluster("creation-provider-test", new Eks.ClusterArgs
            {
                ProviderCredentialOpts = new KubeconfigOptions
                {
                    RoleArn = arn
                },
                CreateOidcProvider = false,
                SkipDefaultNodeGroup = true,
                NodeAssociatePublicIpAddress = false,
                EndpointPrivateAccess = true,
                EndpointPublicAccess = true,
            });
        });        

        
        kubeConfig = cluster.Apply( c => c.KubeconfigJson );  
    }
}
```
