### ISSUE TITLE
Exception when using service_role argument

### ISSUE THREAD

**Issue by 88lexd** [pulumi/pulumi-eks#1120]
### What happened?

When I try creating a service role for the EKS cluster, it crashes Pulumi

### Example

```python
def create_eks_cluster(self, name: str, eks_version: str, nodesMin: int, nodesMax: int, nodesDefaultType: str, nodeTypes: list):
      cluster = eks.Cluster(resource_name,
          version=eks_version,
          cluster_security_group=self._cluster_security_group('eks-sg'),
          vpc_id=self.vpc_id,
          private_subnet_ids=self.private_subnet_ids,
          public_subnet_ids=self.public_subnet_ids,
          enabled_cluster_log_types=cluster_logging,
          encryption_config_key_arn=kms_key.arn,
          endpoint_private_access=True,
          endpoint_public_access=True, # TODO: For testing only!!!!
          public_access_cidrs=['0.0.0.0/0'], # TODO: For testing only!!!!
          create_oidc_provider=True, # https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#create_oidc_provider_python
          node_root_volume_encrypted=True,
          node_root_volume_size=20, # This is the default but specify here anyway
          gpu=True,
          # service_role=self._create_cluster_role(name),
          # =========================>> THIS ARG HERE FAILS, if I remove it, the cluster creates fine
          service_role=aws.iam.Role(
              resource_name,
              assume_role_policy=aws.iam.get_policy_document(statements=[
                  aws.iam.GetPolicyDocumentStatementArgs(
                      effect="Allow",
                      actions=["sts:AssumeRole"],
                      principals=[
                          aws.iam.GetPolicyDocumentStatementPrincipalArgs(
                              type="Service",
                              identifiers=["eks.amazonaws.com"],
                          ),
                      ]
                  )
              ]).json,
              managed_policy_arns=[
                  "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
              ]
          ),
          min_size=nodesMin,
          max_size=nodesMax,
          instance_type=nodesDefaultType
      )
```

Error:
```
Diagnostics:
  pulumi:pulumi:Stack (eks-kubeflow-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 191, in <module>
        loop.run_until_complete(coro)
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 132, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 53, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 86, in wait_for_rpcs
        raise exn from cause
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/invoke.py", line 176, in do_invoke
        inputs = await rpc.serialize_properties(props, {})
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 215, in serialize_properties
        result = await serialize_property(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 359, in serialize_property
        await serialize_property(
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 521, in serialize_property
        k: await serialize_property(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 359, in serialize_property
        await serialize_property(
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 521, in serialize_property
        k: await serialize_property(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 474, in serialize_property
        value = await serialize_property(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 457, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/output.py", line 132, in get_value
        val = await self._future
              ^^^^^^^^^^^^^^^^^^
      File "/Users/alex/git/dha-py-pulumi/venv/lib/python3.12/site-packages/pulumi/output.py", line 178, in run
        value = await self._future
                ^^^^^^^^^^^^^^^^^^
    Exception: invoke of aws:eks/getCluster:getCluster failed: invocation of aws:eks/getCluster:getCluster returned an error: invoking aws:eks/getCluster:getCluster: 1 error occurred:
        * reading EKS Cluster (dev-ad-eks-cluster-eksCluster-c469f39): couldn't find resource
```

### Output of `pulumi about`

Note: No stack provisioned, thought it was something bad so I destroyed everything and still failed to create from scratch..

```
CLI          
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.29.1
eks         2.3.0
kubernetes  4.9.1
python      unknown

Host     
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.12.2'

Backend        
Name           Alexs-MBP
URL            s3://py-pulumi-alex-backend
User           alex.dinh
Organizations  
Token type     personal

Dependencies:
NAME        VERSION
pip         24.0
pulumi_eks  2.3.0
setuptools  69.2.0
wheel       0.43.0

Pulumi locates its logs in /var/folders/md/gh4pql9d307_rmkrswb5xml00000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by 88lexd** [comment]
Nevermind, this is a user error..  the crash is coming from another line in the code.
