### ISSUE TITLE
unable to load schema information from the API server: the server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by nsisodiya** [pulumi/pulumi-eks#296]
I am getting following error

```▶ pulumi up
Previewing update (prod):

     Type                          Name                          Plan     Info
     pulumi:pulumi:Stack           syngenta-platform-prod                 1 error; 18 messages
     └─ kubernetes:core:ConfigMap  syngenta-platform-nodeAccess           1 error
 
Diagnostics:
  pulumi:pulumi:Stack (syngenta-platform-prod):
    Error: invocation of aws:ec2/getSubnet:getSubnet returned an error: grpc: the client connection is closing
        at /home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/@pulumi/pulumi/runtime/invoke.js:172:33
        at Object.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:1210:9)
        at InterceptingListener._callNext (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:847:24)
    Error: invocation of aws:ec2/getSubnet:getSubnet returned an error: grpc: the client connection is closing
        at /home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/@pulumi/pulumi/runtime/invoke.js:172:33
        at Object.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:1210:9)
        at InterceptingListener._callNext (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:847:24)
    Error: invocation of aws:ec2/getSubnet:getSubnet returned an error: grpc: the client connection is closing
        at /home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/@pulumi/pulumi/runtime/invoke.js:172:33
        at Object.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:1210:9)
        at InterceptingListener._callNext (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:847:24)
 
    error: Running program '/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi' failed with an unhandled exception:
    Error: invocation of aws:ec2/getSubnet:getSubnet returned an error: grpc: the client connection is closing
        at /home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/@pulumi/pulumi/runtime/invoke.js:172:33
        at Object.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:1210:9)
        at InterceptingListener._callNext (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/home/narendra/Coding/platform/syngenta-platform-infra-using-pulumi/node_modules/grpc/src/client_interceptors.js:847:24)
 
  kubernetes:core:ConfigMap (syngenta-platform-nodeAccess):
    error: unable to load schema information from the API server: the server has asked for the client to provide credentials
```
Index.js
```"use strict";
const pulumi = require("@pulumi/pulumi");
const aws = require("@pulumi/aws");
const awsx = require("@pulumi/awsx");
const eks = require("@pulumi/eks");

const config = {
  vpcName: "syngenta-platform",
  clusterName: "syngenta-platform"
};
// Create a VPC for our cluster.
const vpc = new awsx.ec2.Vpc(config.vpcName);

// Create the EKS cluster itself with Fargate enabled.
const cluster = new eks.Cluster(config.clusterName, {
  fargate: true,
  vpcId: vpc.id,
  privateSubnetIds: vpc.privateSubnetIds,
  deployDashboard: false
});

// Export the cluster's kubeconfig.
//TODO - make a TypeScript Project
//export const kubeconfig = cluster.kubeconfig;
exports.kubeconfig = cluster.kubeconfig;
```

**Comment by nsisodiya** [comment]
I think the problem is 
```config:
  aws:profile: platform
```
I don't use `default` aws profile.  so I used
```pulumi config set aws:profile platform```

Now that, I removed this config and copied aws creds from `platform` profile to default profile.
I can see, 
```├─ kubernetes:core:ServiceAccount                              syngenta-platform-eks-admin               created``` 
right now, I am running `pulumi up` and seems like it is working. Will update here again.

**Comment by lukehoban** [comment]
Is it possible this is related to https://github.com/pulumi/pulumi-eks/issues/140?  There was a feature added to the library to “fix” that - and it may be that you can use that here?

**Comment by nsisodiya** [comment]
@lukehoban 
Yes, removing profile solve the issue. but I got following error/warning 
```
error: update failed
 
kube-system/kubernetes-dashboard (eks:index:Cluster$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1beta2:Deployment)
error: 4 errors occurred:
	* resource kube-system/kubernetes-dashboard was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'kubernetes-dashboard' timed out waiting to be Ready
	* [MinimumReplicasUnavailable] Deployment does not have minimum availability.
	* [ProgressDeadlineExceeded] ReplicaSet "kubernetes-dashboard-6fd7f9c494" has timed out progressing.
	* Minimum number of live Pods was not attained

 
kube-system/heapster (eks:index:Cluster$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service)
error: 2 errors occurred:
	* resource kube-system/heapster was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'heapster' timed out waiting to be Ready
	* Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods

 
kube-system/kubernetes-dashboard (eks:index:Cluster$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service)
error: 2 errors occurred:
	* resource kube-system/kubernetes-dashboard was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'kubernetes-dashboard' timed out waiting to be Ready
	* Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods

 
kube-system/monitoring-influxdb (eks:index:Cluster$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service)
error: 2 errors occurred:
	* resource kube-system/monitoring-influxdb was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'monitoring-influxdb' timed out waiting to be Ready
	* Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods

 
kube-system/heapster (eks:index:Cluster$kubernetes:yaml:ConfigGroup$kubernetes:extensions/v1beta1:Deployment)
error: 2 errors occurred:
	* resource kube-system/heapster was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'heapster' timed out waiting to be Ready
	* Minimum number of Pods to consider the application live was not attained

 
kube-system/monitoring-influxdb (eks:index:Cluster$kubernetes:yaml:ConfigGroup$kubernetes:extensions/v1beta1:Deployment)
error: 2 errors occurred:
	* resource kube-system/monitoring-influxdb was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'monitoring-influxdb' timed out waiting to be Ready
	* Minimum number of Pods to consider the application live was not attained

 
Resources:
    + created 11
    56 unchanged
 
Duration: 10m42s
```

**Comment by nsisodiya** [comment]
```
$ KUBECONFIG=./kubeconfig.json kubectl get pods -o wide --all-namespaces

NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE   IP             NODE                                   NOMINATED NODE   READINESS GATES
kube-system   aws-node-25429                          0/1     Pending   0          47m   <none>         <none>                                 <none>           <none>
kube-system   aws-node-6j62j                          0/1     Pending   0          47m   <none>         <none>                                 <none>           <none>
kube-system   coredns-7dc94799cb-9fkl6                1/1     Running   0          47m   10.0.183.231   fargate-ip-10-0-183-231.ec2.internal   <none>           <none>
kube-system   coredns-7dc94799cb-zw5h5                1/1     Running   0          47m   10.0.155.107   fargate-ip-10-0-155-107.ec2.internal   <none>           <none>
kube-system   heapster-5d4bf58946-7hrgm               0/1     Pending   0          50m   <none>         <none>                                 <none>           <none>
kube-system   kubernetes-dashboard-6fd7f9c494-jvq9w   0/1     Pending   0          50m   <none>         <none>                                 <none>           <none>
kube-system   monitoring-influxdb-866db5f944-2vgz7    0/1     Pending   0          50m   <none>         <none>                                 <none>           <none>

```

**Comment by metral** [comment]
@nsisodiya Are you still encountering this issue?

**Comment by sylv3r** [comment]
@lukehoban @metral I can confirm this is still an issue : 

With a custom profile (and no `default` one in `~/.aws/credentials`), the `profile` arg in a `aws.Provider` does not seem to be used at all for `pulumi-nodejs:dynamic:Resource` and `kubernetes:core:ConfigMap` : 

```ts
import * as aws from '@pulumi/aws';
import * as eks from '@pulumi/eks';

const awsProvider = new aws.Provider('aws-provider', {
  profile: 'my-custom-profile',
  region: 'eu-west-1',
});

const cluster = new eks.Cluster('cluster-test', {
  fargate: true,
  deployDashboard: false,
}, { provider: awsProvider });
```

Output : 
```
Updating (staging):
     Type                                  Name                               Status                  Info
     pulumi:pulumi:Stack                   clusters-staging                   **failed**              1 error; 11 messages
     └─ eks:index:Cluster                  cluster-test                                     
 +      ├─ kubernetes:core:ConfigMap       cluster-test-nodeAccess  **creating failed**     1 error
 +      └─ pulumi-nodejs:dynamic:Resource  cluster-test-vpc-cni     **creating failed**     1 error
 
Diagnostics:
  kubernetes:core:ConfigMap (cluster-test-nodeAccess):
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get https://2D979A45D4C559CC8769EA9965C38B5A.yl4.eu-west-1.eks.amazonaws.com/openapi/v2?timeout=32s: getting credentials: exec: exit status 1
 
  pulumi:pulumi:Stack (clusters-staging):
    could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
    Unable to connect to the server: getting credentials: exec: exit status 1
 
    could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
    could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 
    could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
    could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 
    error: update failed
```

But if I add a `default` profile in `~/.aws/credentials` : 

```
Updating (staging):
     Type                                  Name                                   Status                  Info
     pulumi:pulumi:Stack                   clusters-staging                       **failed**              1 error
     └─ eks:index:Cluster                  cluster-test                                         
 +      ├─ pulumi-nodejs:dynamic:Resource  cluster-test-vpc-cni         created                 
 +      ├─ kubernetes:core:ConfigMap       cluster-test-nodeAccess      created                 
 +      └─ aws:eks:FargateProfile          cluster-test-fargateProfile  **creating failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (clusters-staging):
    error: update failed
 
  aws:eks:FargateProfile (cluster-test-fargateProfile):
    error: error creating EKS Fargate Profile (cluster-test-eksCluster-a39a7f4:cluster-test-fargateProfile-7b6d330): InvalidParameterException: Subnet subnet-7bf4c133 provided in Fargate Profile is not a private subnet
    {
      Message_: "Subnet subnet-7bf4c133 provided in Fargate Profile is not a private subnet"
    }
```

The resources are created in this case.

I still having an issue with `aws:eks:FargateProfile`, does not seem related though.
Seems like I need to provide the private subnet myself ?

### Context

- I have no `aws:*` config set for the stack, everything is in the file
- pulumi CLI version `1.13.0`
- dependencies : 
```
    "@pulumi/aws": "^1.28.0",
    "@pulumi/awsx": "^0.19.2",
    "@pulumi/eks": "^0.18.24",
    "@pulumi/kubernetes": "^1.6.0",
    "@pulumi/pulumi": "^1.13.1",
```

**Comment by metral** [comment]
> With a custom profile (and no default one in ~/.aws/credentials), the profile arg in a aws.Provider does not seem to be used at all for pulumi-nodejs:dynamic:Resource and kubernetes:core:ConfigMap

> But if I add a default profile in ~/.aws/credentials, the resources are created

Looking at this closer, it appears that though the cluster and other resources are created, the dynamicResource (vpc-cni) and the configmap (aws-auth) are not created, as they rely on the cluster's kubeconfig, which does not factor in the same credentials as you set in the custom AWS Provider.

We're looking into a fix for this.

> I still having an issue with aws:eks:FargateProfile, does not seem related though.
Seems like I need to provide the private subnet myself ?

---

Yes, fargate only works with [private subnets](https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html):
> The IDs of subnets to launch pods into that use this profile. At this time, pods running on Fargate are not assigned public IP addresses, so only private subnets (with no direct route to an Internet Gateway) are accepted for this parameter.
