### ISSUE TITLE
YAMLException: unacceptable kind of an object to dump [object Undefined]

### ISSUE THREAD

**Issue by emiioan** [pulumi/pulumi-eks#396]
Hi,

When I try to add a eks nodegoup to my stack it fails with fallowing error:

  pulumi:pulumi:Stack (eks-test-eksbasev2-stack):
    YAMLException: unacceptable kind of an object to dump [object Undefined]
        at writeNode (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:779:13)
        at writeBlockMapping (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
        at writeNode (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
        at writeBlockSequence (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:542:9)
        at writeNode (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:763:9)
        at writeBlockMapping (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
        at writeNode (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
        at writeBlockMapping (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
        at writeNode (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
        at writeBlockMapping (/home/emi/ops/pulumi/modules/nodepool/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)

Any ideea if this is a bug in pulumi-eks or a user error inside my code? The error doesn't lead me to anything specific and I'm stuck. Much appreciate some help from you guys! Thanks.

**Comment by emiioan** [comment]
Forgot to add that it fails when it tries to create the cloudformation stack. The rest of the nodegroups aws resources like launchconfiguration, keypair, provider etc are created fine.

**Comment by leezen** [comment]
Could you please provide code to help reproduce?
