### ISSUE TITLE
Confusing error when supplying over-specified cluster version

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-eks#438]
### Problem description

Running `pulumi up` with an over-specified version crashes the program with an unhelpful error. See below.

### Errors & Logs

```sh
$ pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/hausdorff/eks-upgrade-test/dev/previews/12575c07-1a89-4328-bb89-87ea6ddb9146

     Type                                    Name                                       Plan       Info
 +   pulumi:pulumi:Stack                     eks-upgrade-test-dev                       create     1 error
 +   ├─ eks:index:Cluster                    cluster                                    create
 +   │  ├─ eks:index:ServiceRole             cluster-eksRole                            create
 +   │  │  ├─ aws:iam:Role                   cluster-eksRole-role                       create
 +   │  │  ├─ aws:iam:RolePolicyAttachment   cluster-eksRole-4b490823                   create
 +   │  │  └─ aws:iam:RolePolicyAttachment   cluster-eksRole-90eb1c99                   create
 +   │  ├─ eks:index:ServiceRole             cluster-instanceRole                       create
 +   │  │  ├─ aws:iam:Role                   cluster-instanceRole-role                  create
 +   │  │  ├─ aws:iam:RolePolicyAttachment   cluster-instanceRole-03516f97              create
 +   │  │  ├─ aws:iam:RolePolicyAttachment   cluster-instanceRole-e1b295bd              create
 +   │  │  └─ aws:iam:RolePolicyAttachment   cluster-instanceRole-3eb088f2              create
 +   │  ├─ pulumi-nodejs:dynamic:Resource    cluster-cfnStackName                       create
 +   │  ├─ aws:iam:InstanceProfile           cluster-instanceProfile                    create
 +   │  ├─ aws:ec2:SecurityGroup             cluster-eksClusterSecurityGroup            create
 +   │  ├─ aws:ec2:SecurityGroupRule         cluster-eksClusterInternetEgressRule       create
 +   │  ├─ aws:eks:Cluster                   cluster-eksCluster                         create
 +   │  ├─ pulumi:providers:kubernetes       cluster-eks-k8s                            create
 +   │  ├─ pulumi-nodejs:dynamic:Resource    cluster-vpc-cni                            create
 +   │  ├─ kubernetes:core:ConfigMap         cluster-nodeAccess                         create
 +   │  ├─ aws:ec2:SecurityGroup             cluster-nodeSecurityGroup                  create
 +   │  ├─ aws:ec2:SecurityGroupRule         cluster-eksClusterIngressRule              create
 +   │  ├─ aws:ec2:SecurityGroupRule         cluster-eksExtApiServerClusterIngressRule  create
 +   │  ├─ aws:ec2:SecurityGroupRule         cluster-eksNodeIngressRule                 create
 +   │  ├─ aws:ec2:SecurityGroupRule         cluster-eksNodeClusterIngressRule          create
 +   │  └─ aws:ec2:SecurityGroupRule         cluster-eksNodeInternetEgressRule          create
 +   └─ awsx:x:ec2:Vpc                       vpc                                        create
 +      ├─ awsx:x:ec2:NatGateway             vpc-0                                      create
 +      │  ├─ aws:ec2:Eip                    vpc-0                                      create
 +      │  └─ aws:ec2:NatGateway             vpc-0                                      create
 +      ├─ awsx:x:ec2:Subnet                 vpc-private-0                              create
 +      │  ├─ aws:ec2:Subnet                 vpc-private-0                              create
 +      │  ├─ aws:ec2:RouteTable             vpc-private-0                              create
 +      │  ├─ aws:ec2:RouteTableAssociation  vpc-private-0                              create
 +      │  └─ aws:ec2:Route                  vpc-private-0-nat-0                        create
 +      ├─ awsx:x:ec2:InternetGateway        vpc                                        create
 +      │  └─ aws:ec2:InternetGateway        vpc                                        create
 +      ├─ awsx:x:ec2:Subnet                 vpc-public-0                               create
 +      │  ├─ aws:ec2:RouteTable             vpc-public-0                               create
 +      │  ├─ aws:ec2:Subnet                 vpc-public-0                               create
 +      │  ├─ aws:ec2:RouteTableAssociation  vpc-public-0                               create
 +      │  └─ aws:ec2:Route                  vpc-public-0-ig                            create
 +      ├─ awsx:x:ec2:Subnet                 vpc-private-1                              create
 +      │  ├─ aws:ec2:RouteTable             vpc-private-1                              create
 +      │  ├─ aws:ec2:Subnet                 vpc-private-1                              create
 +      │  ├─ aws:ec2:RouteTableAssociation  vpc-private-1                              create
 +      │  └─ aws:ec2:Route                  vpc-private-1-nat-1                        create
 +      ├─ aws:ec2:Vpc                       vpc                                        create
 +      ├─ awsx:x:ec2:NatGateway             vpc-1                                      create
 +      │  ├─ aws:ec2:Eip                    vpc-1                                      create
 +      │  └─ aws:ec2:NatGateway             vpc-1                                      create
 +      └─ awsx:x:ec2:Subnet                 vpc-public-1                               create
 +         ├─ aws:ec2:RouteTable             vpc-public-1                               create
 +         ├─ aws:ec2:Subnet                 vpc-public-1                               create
 +         ├─ aws:ec2:Route                  vpc-public-1-ig                            create
 +         └─ aws:ec2:RouteTableAssociation  vpc-public-1                               create

Diagnostics:
  pulumi:pulumi:Stack (eks-upgrade-test-dev):
    error: Running program '/Users/alex/src/moment-eng/eks-upgrade' failed with an unhandled exception:
    Error: invocation of aws:ssm/getParameter:getParameter returned an error: invoking aws:ssm/getParameter:getParameter: Error describing SSM parameter: ParameterNotFound:
        at /Users/alex/src/moment-eng/eks-upgrade/node_modules/@pulumi/pulumi/runtime/invoke.js:136:33
        at Http2CallStream.<anonymous> (/Users/alex/src/moment-eng/eks-upgrade/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:327:22)
        at Http2CallStream.EventEmitter.emit (domain.js:485:12)
        at /Users/alex/src/moment-eng/eks-upgrade/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

### Affected product version(s)

Fresh install of `pulumi` from `brew`:

```sh
$ pulumi version
v2.10.0
```

### Reproducing the issue

On fresh `pulumi new https://github.com/pulumi/examples/tree/master/aws-ts-eks`, the following `version` fails:

```typescript
```

**Comment by stack72** [comment]
We should be able to understand if `return pulumi.output(aws.ssm.getParameter({name: parameterName}, {parent, async: true})).value;` returns an error and if so, bubble a better up a better user error
