### ISSUE TITLE
Golang: library unusable: panic: reflect: Elem of invalid type interface {}

### ISSUE THREAD

**Issue by universam1** [pulumi/pulumi-eks#577]
Library seem to be broken regarding Golang, including the basic example

https://github.com/pulumi/pulumi-eks/tree/master/examples/managed-nodegroups-go

## Expected behavior
to build 

## Current behavior

```
Previewing update (sam):
     Type                             Name                       Plan       Info
 +   pulumi:pulumi:Stack              managed-nodegroups-go-sam  create     1 error; 15 messages
 +   ├─ aws:iam:Role                  example-role0              create     
 +   ├─ aws:iam:Role                  example-role1              create     
 +   ├─ aws:iam:RolePolicyAttachment  example-role0-policy-2     create     
 +   ├─ aws:iam:RolePolicyAttachment  example-role0-policy-1     create     
 +   ├─ aws:iam:RolePolicyAttachment  example-role0-policy-0     create     
 +   └─ aws:iam:Role                  example-role2              create     
 
Diagnostics:
  pulumi:pulumi:Stack (managed-nodegroups-go-sam):
    panic: reflect: Elem of invalid type interface {}
    goroutine 68 [running]:
    reflect.(*rtype).Elem(0x10f77c0, 0xc0000c5d80, 0x194)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.16.3_1/libexec/src/reflect/type.go:915 +0x1a5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs(0x14ba8b8, 0xc000130010, 0x11e7f80, 0xc00024f040, 0x16, 0x10f77c0, 0xc0000c5d80, 0x194, 0x0, 0x0, ...)
        /home/sam/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/pulumi/types.go:625 +0x2512
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs(0x14ba8b8, 0xc000130010, 0x10f77c0, 0xc0000d0120, 0x194, 0x10f77c0, 0xc0000c5d80, 0x194, 0x0, 0x0, ...)
        /home/sam/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/pulumi/types.go:644 +0xc68
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs(0x14ba8b8, 0xc000130010, 0x101d360, 0xc0000ce138, 0x97, 0x101d360, 0xc0000ce198, 0x197, 0x0, 0x0, ...)
        /home/sam/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/pulumi/types.go:680 +0x17a8
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.toOutputWithContext.func1(0x101d360, 0xc0000ce138, 0x14cf148, 0xc0001d2230, 0x14de620, 0x101d360, 0x14ba8b8, 0xc000130010, 0x0)
        /home/sam/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/pulumi/types.go:753 +0x16e
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.toOutputWithContext
        /home/sam/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/pulumi/types.go:745 +0x1eb
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

## Steps to reproduce
trying to run https://github.com/pulumi/pulumi-eks/tree/master/examples/managed-nodegroups-go

## Context (Environment)
Bumping the version to v0.30.0 does not help

## Affected feature

Library is basically broken for Golang

**Comment by lblackstone** [comment]
I was able to reproduce this, and it seems like there may be some problems with the output properties of the cluster. This portion of the example works for me:

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/iam"
	"github.com/pulumi/pulumi-eks/sdk/go/eks"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var managedPolicyArns = []string{
	"arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
	"arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
	"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
}

func createRole(ctx *pulumi.Context, name string) (*iam.Role, error) {
	version := "2012-10-17"
	statementId := "AllowAssumeRole"
	effect := "Allow"
	instanceAssumeRolePolicy, err := iam.GetPolicyDocument(ctx, &iam.GetPolicyDocumentArgs{
		Version: &version,
		Statements: []iam.GetPolicyDocumentStatement{
			{
				Sid:    &statementId,
				Effect: &effect,
				Actions: []string{
					"sts:AssumeRole",
				},
				Principals: []iam.GetPolicyDocumentStatementPrincipal{
					{
						Type: "Service",
						Identifiers: []string{
							"ec2.amazonaws.com",
						},
					},
				},
			},
		},
	}, nil)
	if err != nil {
		return nil, err
	}
	role, err := iam.NewRole(ctx, name, &iam.RoleArgs{
		AssumeRolePolicy: pulumi.String(instanceAssumeRolePolicy.Json),
	})
	if err != nil {
		return nil, err
	}

	for i, policy := range managedPolicyArns {
		_, err := iam.NewRolePolicyAttachment(ctx, fmt.Sprintf("%s-policy-%d", name, i), &iam.RolePolicyAttachmentArgs{
			PolicyArn: pulumi.String(policy),
			Role:      role.ID(),
		})
		if err != nil {
			return nil, err
		}
	}
	return role, nil
}

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		role0, err := createRole(ctx, "example-role0")
		if err != nil {
			return err
		}
		role1, err := createRole(ctx, "example-role1")
		if err != nil {
			return err
		}
		role2, err := createRole(ctx, "example-role2")
		if err != nil {
			return err
		}

		cluster, err := eks.NewCluster(ctx, "example-managed-nodegroups-go", &eks.ClusterArgs{
			SkipDefaultNodeGroup: pulumi.BoolPtr(true),
			InstanceRoles: iam.RoleArray{
				role0,
				role1,
				role2,
			},
			ProviderCredentialOpts: &eks.KubeconfigOptionsArgs{
				ProfileName: pulumi.String("pulumi-dev-sandbox"),
			},
		})
		if err != nil {
			return err
		}

		// Export the kubeconfig for the cluster
		ctx.Export("kubeconfig", cluster.Kubeconfig)

		return nil
	})
}
```

However, I keep hitting errors trying to create additional ManagedNodeGroups. Adding this snippet gives me the following error:

```go
		// Create a simple AWS managed node group using a cluster as input and the
		// refactored API.
		_, err = eks.NewManagedNodeGroup(ctx, "aws-managed-ng0",
			&eks.ManagedNodeGroupArgs{
				Cluster:  cluster.Core,
				NodeRole: role0,
			})
		if err != nil {
			return err
		}
```
```
error: program failed: waiting for RPCs: marshaling properties: awaiting input property cluster: cannot marshal an input of type pulumi.StringOutput with element type string as a value of type pulumi.StringOutput
    exit status 1
```

I'm still trying to track down why this is.

**Comment by viveklak** [comment]
I remember testing this manually originally when added in https://github.com/pulumi/pulumi-eks/pull/532 - note the callout for https://github.com/pulumi/pulumi-eks/issues/530 in the PR text. Perhaps that helps track down what changed to be causing this issue now?

**Comment by lblackstone** [comment]
This appears to be related to https://github.com/pulumi/pulumi-eks/issues/566

**Comment by justinvp** [comment]
With the codegen changes in https://github.com/pulumi/pulumi/pull/7158 applied, I'm able to successfully deploy @lblackstone's repro:

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/iam"
	"github.com/pulumi/pulumi-eks/sdk/go/eks"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var managedPolicyArns = []string{
	"arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
	"arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
	"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
}

func createRole(ctx *pulumi.Context, name string) (*iam.Role, error) {
	version := "2012-10-17"
	statementId := "AllowAssumeRole"
	effect := "Allow"
	instanceAssumeRolePolicy, err := iam.GetPolicyDocument(ctx, &iam.GetPolicyDocumentArgs{
		Version: &version,
		Statements: []iam.GetPolicyDocumentStatement{
			{
				Sid:    &statementId,
				Effect: &effect,
				Actions: []string{
					"sts:AssumeRole",
				},
				Principals: []iam.GetPolicyDocumentStatementPrincipal{
					{
						Type: "Service",
						Identifiers: []string{
							"ec2.amazonaws.com",
						},
					},
				},
			},
		},
	}, nil)
	if err != nil {
		return nil, err
	}
	role, err := iam.NewRole(ctx, name, &iam.RoleArgs{
		AssumeRolePolicy: pulumi.String(instanceAssumeRolePolicy.Json),
	})
	if err != nil {
		return nil, err
	}

	for i, policy := range managedPolicyArns {
		_, err := iam.NewRolePolicyAttachment(ctx, fmt.Sprintf("%s-policy-%d", name, i), &iam.RolePolicyAttachmentArgs{
			PolicyArn: pulumi.String(policy),
			Role:      role.ID(),
		})
		if err != nil {
			return nil, err
		}
	}
	return role, nil
}

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		role0, err := createRole(ctx, "example-role0")
		if err != nil {
			return err
		}
		role1, err := createRole(ctx, "example-role1")
		if err != nil {
			return err
		}
		role2, err := createRole(ctx, "example-role2")
		if err != nil {
			return err
		}

		cluster, err := eks.NewCluster(ctx, "example-managed-nodegroups-go", &eks.ClusterArgs{
			SkipDefaultNodeGroup: pulumi.BoolPtr(true),
			InstanceRoles: iam.RoleArray{
				role0,
				role1,
				role2,
			},
			ProviderCredentialOpts: &eks.KubeconfigOptionsArgs{
				ProfileName: pulumi.String("pulumi-dev-sandbox"),
			},
		})
		if err != nil {
			return err
		}

		// Export the kubeconfig for the cluster
		ctx.Export("kubeconfig", cluster.Kubeconfig)

		// Create a simple AWS managed node group using a cluster as input and the
		// refactored API.
		_, err = eks.NewManagedNodeGroup(ctx, "aws-managed-ng0",
			&eks.ManagedNodeGroupArgs{
				Cluster:  cluster.Core,
				NodeRole: role0,
			})
		if err != nil {
			return err
		}

		return nil
	})
}
```
