### ISSUE TITLE
Adding security group pointer to eks.NodeGroupArgs.ExtraNodeSecurityGroups throws an error

### ISSUE THREAD

**Issue by fiibbb** [pulumi/pulumi-eks#616]
Adding a security group pointer to ` eks.NodeGroupArgs.ExtraNodeSecurityGroups` doesn't seem to work as it throws an error, even though it's allowed by the type system. This prevents adding the same security group (such as a self-referential one) to multiple node grouops.

Of course, I could be misusing the API. In that case, would be happy to learn how I should make multiple node groups use the same security group.

## Steps to reproduce
1.  Create a self-referential security group:
```
	sg, _ := ec2.NewSecurityGroup(ctx, "test-sg", &ec2.SecurityGroupArgs{
		Name:        pulumi.String("test-sg"),
		VpcId:       vpc.ID(),
		Ingress: ec2.SecurityGroupIngressArray{
			ec2.SecurityGroupIngressArgs{
				Self:        pulumi.Bool(true),
				Protocol:    pulumi.String("all"),
				FromPort:    pulumi.Int(0),
				ToPort:      pulumi.Int(0),
			},
		},
	})
```
2. Create a eks NodeGroup with the above security group as an `ExtraNodeSecurityGroups`:
```
	// ... create the cluster and provider
	nodeGroup, _ := eks.NewNodeGroup(ctx, "test-ng", &eks.NodeGroupArgs{
		...
		ExtraNodeSecurityGroups: ec2.SecurityGroupArray{
			sg, // <<<<===== Note this is referencing the security group created in step 1.
		}
	})
```
3. Run `pulumi up`

## Expected:
The node group gets created with an extra security group attached.

## Actual:
An error is thrown:
```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-go-k8s-dev):
    TypeError: args.extraNodeSecurityGroups.map is not a function: TypeError: args.extraNodeSecurityGroups.map is not a function
        at createNodeGroup (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/nodegroup.ts:405:99)
        at new NodeGroup (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/nodegroup.ts:319:23)
        at Object.construct (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/cmd/provider/nodegroup.ts:21:31)
        at Provider.construct (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/cmd/provider/index.ts:104:24)
        at Server.<anonymous> (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/pulumi/provider/server.js:300:52)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/pulumi/provider/server.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    TypeError: args.extraNodeSecurityGroups.map is not a function: TypeError: args.extraNodeSecurityGroups.map is not a function
        at createNodeGroup (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/nodegroup.ts:405:99)
        at new NodeGroup (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/nodegroup.ts:319:23)
        at Object.construct (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/cmd/provider/nodegroup.ts:21:31)
        at Provider.construct (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/cmd/provider/index.ts:104:24)
        at Server.<anonymous> (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/pulumi/provider/server.js:300:52)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/<some-user>/.pulumi/plugins/resource-eks-v0.32.0/node_modules/@pulumi/pulumi/provider/server.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

    error: program failed: waiting for RPCs: rpc error: code = Unknown desc = args.extraNodeSecurityGroups.map is not a function
    exit status 1

    error: an unhandled error occurred: program exited with non-zero exit code: 1

```

**Comment by fiibbb** [comment]
Additional context: I'm using v3.11.0

**Comment by pgavlin** [comment]
@fiibbb can you share verbose logs from the failing update (`pulumi up -v=9 --logtostderr 2>out`)? If so, please email the logs to me directly.

**Comment by TomStuart92** [comment]
Was any progress made on this @pgavlin, @fiibbb? We're seeing the exact same issue today. Happy to supply logs if useful 😄

**Comment by pasta88** [comment]
I am facing the same issue:

    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 82, in wait_for_rpcs
        raise exn from cause
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 921, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 918, in do_rpc_call
        handle_grpc_error(exn)
      File "/Users/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pulumi/runtime/settings.py", line 273, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: args.extraNodeSecurityGroups.map is not a function

    TypeError: args.extraNodeSecurityGroups.map is not a function: TypeError: args.extraNodeSecurityGroups.map is not a function
        at createNodeGroupInternal (/snapshot/eks/bin/nodegroup.js:225:40)
        at new NodeGroupInternal (/snapshot/eks/bin/nodegroup.js:79:23)
        at Object.construct (/snapshot/eks/bin/cmd/provider/nodegroup.js:21:31)
        at Provider.construct (/snapshot/eks/bin/cmd/provider/index.js:129:100)
        at Server.<anonymous> (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:315:52)
        at Generator.next (<anonymous>)
        at fulfilled (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
