### ISSUE TITLE
Unexpectedly need to pass instanceProfile to managedNodeGroup

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-eks#769]
### What happened?

I'm trying to create an EKS cluster in Python with managedNodeGroups attached, and every time I do, I get yelled at for not passing an instanceProfile.

The [example](https://github.com/pulumi/pulumi-eks/tree/master/examples/managed-nodegroups-py) doesn't pass one, so either:

- something has changed and the tests aren't running correctly
- I'm doing something wrong

### Steps to reproduce

Create a VPC, cluster and managed node group like so:

```python

import pulumi
import pulumi_eks as eks
import pulumi_aws as aws
import pulumi_kubernetes as k8s
import pulumi_awsx as awsx

vpc = awsx.ec2.Vpc(
    "patch",
    cidr_block="172.1.0.0/22",
)

node_role = aws.iam.Role(
    "patch-system-nodes",
    assume_role_policy=json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "AllowAssumeRole",
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "ec2.amazonaws.com",
                    },
                    "Action": "sts:AssumeRole",
                }
            ],
        }
    ),
)

required_policies = [
    "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
]

for i, policy in enumerate(required_policies):
    # Create RolePolicyAttachment without returning it.
    aws.iam.RolePolicyAttachment(
        f"patch-system-nodes-policy-{i}", policy_arn=policy, role=node_role.id
    )

cluster = eks.Cluster(
    "patch",
    vpc_id=vpc.vpc_id,
    provider_credential_opts=eks.KubeconfigOptionsArgs(
        profile_name="pulumi-dev-sandbox"
    ),
    private_subnet_ids=vpc.private_subnet_ids,
    public_subnet_ids=vpc.public_subnet_ids,
    instance_type="t2.medium",
    min_size=1,
    max_size=1,
    desired_capacity=1,
    create_oidc_provider=True,
    instance_roles=[node_role],
)

 system_nodes = eks.ManagedNodeGroup(
     "patch-system-nodes",
     cluster=cluster.core,
     node_role_arn=node_role.arn,
     subnet_ids=vpc.private_subnet_ids,
     scaling_config=aws.eks.NodeGroupScalingConfigArgs(
         desired_size=1,
         min_size=1,
         max_size=2,
     ),
     disk_size=20,
     instance_types=["t2.medium"],
     taints=[
         aws.eks.NodeGroupTaintArgs(
             effect="NO_SCHEDULE", key="dedicated", value="system"
         )
     ],
     opts=pulumi.ResourceOptions(parent=cluster),
 )
```

### Expected Behavior

It creates the cluster and a managed node group

### Actual Behavior

this error:

```
Diagnostics:
  pulumi:pulumi:Stack (eks_patch_coredns-dev):
    Error: an instanceProfile is required: Error: an instanceProfile is required
        at Object.createNodeGroup (/Users/lbriggs/.pulumi/plugins/resource-eks-v0.41.2/node_modules/@pulumi/nodegroup.ts:382:15)
        at new Cluster (/Users/lbriggs/.pulumi/plugins/resource-eks-v0.41.2/node_modules/@pulumi/cluster.ts:1458:37)
        at Object.construct (/Users/lbriggs/.pulumi/plugins/resource-eks-v0.41.2/node_modules/@pulumi/cmd/provider/cluster.ts:21:29)
        at Provider.construct (/Users/lbriggs/.pulumi/plugins/resource-eks-v0.41.2/node_modules/@pulumi/cmd/provider/index.ts:123:24)
        at Server.<anonymous> (/Users/lbriggs/.pulumi/plugins/resource-eks-v0.41.2/node_modules/@pulumi/provider/server.ts:324:48)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/lbriggs/.pulumi/plugins/resource-eks-v0.41.2/node_modules/@pulumi/pulumi/provider/server.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/lbriggs/src/github/jaxxstorm/pulumi-examples/python/aws/eks_patch_coredns/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 602, in do_rpc_call
        return monitor.RegisterResource(req)
      File "/Users/lbriggs/src/github/jaxxstorm/pulumi-examples/python/aws/eks_patch_coredns/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/Users/lbriggs/src/github/jaxxstorm/pulumi-examples/python/aws/eks_patch_coredns/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    	status = StatusCode.UNKNOWN
    	details = "an instanceProfile is required"
    	debug_error_string = "{"created":"@1661916331.907788000","description":"Error received from peer ipv4:127.0.0.1:56686","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"an instanceProfile is required","grpc_status":2}"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jaxxstorm** [comment]
The current workaround for this is as follows:

```
PROFILE = os.getenv("AWS_PROFILE")
if PROFILE is not None:
    raise Exception(
        "AWS_PROFILE is set. Setting AWS_PROFILE can cause issues for EKS. Please use https://github.com/jaxxstorm/aws-sso-creds to get temporary credentials and then unset AWS_PROFILE"
    )
```

This is a defensive piece of code that stops the AWS profile from inadvertently breaking your workflow.

You can then do the following:

- Download and install https://github.com/jaxxstorm/aws-sso-creds
- set your profile and login `export AWS_PROFILE=foo`
- retrieve temporary credentials `eval $(aws-sso-creds export)`
- unset the AWS profile so it's not automatically added `unset AWS_PROFILE`

**Comment by MrOplus** [comment]
any update on this?

**Comment by mjeffryes** [comment]
Verified that this still reproduces on the latest version. It's clear that the test is running (eg see [Bump pu/pu to 3.173 (#1788) · pulumi/pulumi-eks@ec2f8ef](https://github.com/pulumi/pulumi-eks/actions/runs/15448849562/job/43765727682)), so there must be some subtle difference in what it's doing vs this sample code. At very minimum, seems like we ought to understand the cause and document. (The error is a local config validation in the provider, so it should be something we can control.)
