### ISSUE TITLE
Failed to create NodeGroupV2: invocation of aws:ec2/getAmi:getAmi returned an error

### ISSUE THREAD

**Issue by ziye-dm** [pulumi/pulumi-eks#844]
### What happened?

We want to deploy a k8s in a region different with the default region (which pulumi used to login the s3 backend), and to use custom ami for nodes.
Failed to create NodeGroupV2 since the sdk does not set provider https://github.com/pulumi/pulumi-eks/blob/ca1bfd066f0e59593a41ac30910be24f6bbf5c43/nodejs/eks/nodegroup.ts#L1191:
```
error: Error: invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
        * Your query returned no results. Please change your search criteria and try again.


    at Object.callback (/snapshot/eks/node_modules/@pulumi/pulumi/runtime/invoke.js:161:33)
    at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client.ts:338:26)
    at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /snapshot/eks/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
error: Program failed with an unhandled exception:
Traceback (most recent call last):
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 617, in do_rpc_call
    return monitor.RegisterResource(req)
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
        * Your query returned no results. Please change your search criteria and try again.

"
        debug_error_string = "{"created":"@1672821634.765990101","description":"Error received from peer ipv4:127.0.0.1:42247","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:\n\t* Your query returned no results. Please change your search criteria and try again.\n\n","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pulumi/pulumi-language-python-exec", line 192, in <module>
    loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
    await run_pulumi_func(lambda: Stack(func))
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
    await wait_for_rpcs()
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
    raise exception
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/output.py", line 169, in run
    is_known = await self._is_known
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
    result = await rpc
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/output.py", line 100, in is_value_known
    return await is_known and not contains_unknowns(await future)
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/output.py", line 100, in is_value_known
    return await is_known and not contains_unknowns(await future)
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/output.py", line 100, in is_value_known
    return await is_known and not contains_unknowns(await future)
  [Previous line repeated 29 more times]
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 622, in do_register
    resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 619, in do_rpc_call
    handle_grpc_error(exn)
  File "/home/z/work/IacPulumi/venv/lib/python3.8/site-packages/pulumi/runtime/settings.py", line 273, in handle_grpc_error
    raise grpc_error_to_exception(exn)
Exception: invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
        * Your query returned no results. Please change your search criteria and try again.
```

### Steps to reproduce

1. `pulumi login` to the s3 by region A 
2. Create pulumi provider with region B
3. Get ami id `ami-id-Axxx` in A & `ami-id-Bxxx` in B
4. Add NodeGroupV2 in k8s `cluster` like
```
            ng = pulumi_eks.NodeGroupV2(
                f"{prefix}-ng-{node_pool.name}",
                opts=pulumi.ResourceOptions(
                    parent=cluster,
                    provider=provider,
                ),
                cluster=cluster,
                ami_id="ami-id-Axxx",
                ...
            )
```
5. Run `pulumi preview` and failed
6. Update the ami_id arg as "ami-id-Bxxx" and succeeded to run `pulumi preview`

### Expected Behavior

Set the right `ami_id` to create the node group!

### Actual Behavior

Can not use the right `ami_id`!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Thank you for reporting this, @ziye-dm! I will notify the right team members.

@roothorp at first glance it seems we're neglecting to use the optional provider, when given, in [`createNodeGroupV2Internal`](https://github.com/pulumi/pulumi-eks/blob/ca1bfd066f0e59593a41ac30910be24f6bbf5c43/nodejs/eks/nodegroup.ts#L938), e.g. in L1058 where `awsRegion` is queried.

**Comment by ziye-dm** [comment]
@thomas11 @roothorp Hi I just added one line and it's working (built provider binary and moved to $GOPATH/bin):
```
diff --git a/nodejs/eks/nodegroup.ts b/nodejs/eks/nodegroup.ts
index b728478..0a81697 100644
--- a/nodejs/eks/nodegroup.ts
+++ b/nodejs/eks/nodegroup.ts
@@ -1043,7 +1043,7 @@ ${customUserData}
                 values: [id],
             },
         ],
-    })).blockDeviceMappings[0].deviceName;
+    }, { parent, provider})).blockDeviceMappings[0].deviceName;
```
Anyway to release this change? (Glad to open a PR but need permission first?)

**Comment by thomas11** [comment]
Hi @ziye-dm, that's great, thank you! You should have permission to open a PR, just not to merge it.

I still wonder about this line (1058). Shouldn't we add `provider there, too?
```go
const awsRegion = pulumi.output(aws.getRegion({}, { parent, async: true }));
```

**Comment by ziye-dm** [comment]
> Hi @ziye-dm, that's great, thank you! You should have permission to open a PR, just not to merge it.
> 
> I still wonder about this line (1058). Shouldn't we add `provider there, too?
> 
> ```go
> const awsRegion = pulumi.output(aws.getRegion({}, { parent, async: true }));
> ```

Thanks for your quick reply! Looks we should. I just opened a PR https://github.com/pulumi/pulumi-eks/pull/846 and added provider options on all places. Please comment there if any change is wrong.
