### ISSUE TITLE
Updating cluster version from `1.21` -> `1.22` throws `TypeError: Cannot read properties of null (reading 'data')` on random previews.

### ISSUE THREAD

**Issue by Sefiris** [pulumi/pulumi-eks#851]
### What happened?

# Context
I'm attempting to update my staging cluster from kubernetes `1.21` -> `1.22`, this update is required before Feb 15 because of the deprecation of `1.21`.

All of my pulumi runs always run through a pipeline in azure devops, nobody else has access to even run them locally. Now during the preview with the only change in question being changing the cluster version from `1.21` to `1.22` the previews show the errors under actual behaviour.

Now comes the weird part, this pipeline in question runs the preview 3 times, once normally, once detailed and once normally but outputting to a file. One of these will randomly get this below error and after 3-8 times they will all go successfully.

This does not however inspire a-lot of confidence in the upgrade for me when the preview randomly fails. So my question here is am i doing anything obviously wrong? are we even meant to be able to upgrade the version of our clusters?

### Steps to reproduce

Re-running the pipeline, even when it has run successfully once every 3-8 times

### Expected Behavior

The error throws either all the time so that i can fix it, or it doesnt throw at all

### Actual Behavior

Throws below error randomly during one of the 3 previews in the pipeline.
```
...
 ~  aws:eks:Cluster alpha-v1-alpha-01-eks-eksCluster update [diff: ~version]
    pulumi:pulumi:Stack alpha-v1-dev running TypeError: Cannot read properties of null (reading 'data'): TypeError: Cannot read properties of null (reading 'data')
    pulumi:pulumi:Stack alpha-v1-dev running     at /home/azpagent_azpcontainer/.pulumi/plugins/resource-eks-v0.42.2/node_modules/@pulumi/cluster.ts:586:103
    pulumi:pulumi:Stack alpha-v1-dev running     at /home/azpagent_azpcontainer/.pulumi/plugins/resource-eks-v0.42.2/node_modules/@pulumi/output.ts:383:31
    pulumi:pulumi:Stack alpha-v1-dev running     at Generator.next (<anonymous>)
    pulumi:pulumi:Stack alpha-v1-dev running     at /home/azpagent_azpcontainer/.pulumi/plugins/resource-eks-v0.42.2/node_modules/@pulumi/pulumi/output.js:21:71
    pulumi:pulumi:Stack alpha-v1-dev running     at new Promise (<anonymous>)
    pulumi:pulumi:Stack alpha-v1-dev running     at __awaiter (/home/azpagent_azpcontainer/.pulumi/plugins/resource-eks-v0.42.2/node_modules/@pulumi/pulumi/output.js:17:12)
    pulumi:pulumi:Stack alpha-v1-dev running     at applyHelperAsync (/home/azpagent_azpcontainer/.pulumi/plugins/resource-eks-v0.42.2/node_modules/@pulumi/pulumi/output.js:236:12)
    pulumi:pulumi:Stack alpha-v1-dev running     at /home/azpagent_azpcontainer/.pulumi/plugins/resource-eks-v0.42.2/node_modules/@pulumi/output.ts:302:65
    pulumi:pulumi:Stack alpha-v1-dev running     at processTicksAndRejections (node:internal/process/task_queues:96:5)
...
```

### Output of `pulumi about`

```
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.27.0
eks         0.42.2
kubernetes  3.19.3
mysql       3.1.0
python      unknown
random      4.8.2

Host     
OS       darwin
Version  12.6
Arch     arm64

This project is written in python: executable='[redacted]/venv/bin/python3' version='3.9.16
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/[redacted]
User           [redacted]
Organizations  [redacted]

Dependencies:
NAME                      VERSION
artifacts-keyring         0.3.2
buck-account-defaults     1.8.2
buck-crossguard-defaults  0.5.5
pip                       22.2.2
pulumi-eks                0.42.2
pulumi-mysql              3.1.0
pulumi-random             4.8.2
pylint                    2.14.3
```

### Additional context

# Code examples in question

pulumi-eks function is wrapped under a function that was created by me named `create_simple_cluster`
```py
    cluster = eks.Cluster(f'{cluster_name}',
        eks.ClusterArgs(
            name=f"{cluster_name}",
            endpoint_private_access = endpoint_private_access,
            endpoint_public_access = endpoint_public_access,
            skip_default_node_group = True,
            create_oidc_provider=create_oidc_provider,
            node_associate_public_ip_address = False,
            instance_role = mng_shared_iam_role,
            # instance_roles = [ role1 ],
            version = cluster_version,
...
```
Which is called by using the below function
```py
    alpha_01_eks_cluster = eks.create_simple_cluster(
        cluster_name=const.EKS_ALPHA_01_NAME,
        cluster_version="1.22",
        vpc_id=net.vpc.id,
        endpoint_public_access=False,
...
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @Sefiris, thank you so much for the detailed report! This looks indeed concerning. However, before we investigate further, are you able to upgrade to the latest pulumi-eks 1.0.1? There have been a number of changes since the version you're using.

**Comment by Sefiris** [comment]
Have attempted it in the preview to `1.0.1` but it runs in the same issue.
First of all it requires me to add the following lines in the pipeline
```
pulumi plugin install resource aws v5.16.2
pulumi plugin install resource kubernetes v3.23.0
```
Because else it throws the errors
```
pulumi:providers:aws default_5_16_2  error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.16.2 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.16.2`
```
But even with the above `plugin install` commands it still eventually runs into the `Cannot read properties of undefined (reading 'map')` error.
```
    Exception: Cannot read properties of undefined (reading 'map')
    error: TypeError: Cannot read properties of undefined (reading 'map')
        at /snapshot/eks/bin/nodegroup.js:892:32
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:257:35
        at Generator.next (<anonymous>)
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/snapshot/eks/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/snapshot/eks/node_modules/@pulumi/pulumi/output.js:236:12)
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:190:65
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```
This happens with the cluster being on version `1.21` not even upgrading to `1.22`.
Even with the preview erroring though it seems that this upgrade path is breaking as the following replacements occur which would break my clusters in the process
```
 ~  pulumi:providers:kubernetes [REDACTED]-eks-01-eks-k8s update [diff: ~version]
 ~  pulumi:providers:kubernetes [REDACTED]-eks-01-provider update [diff: ~version]
 -- aws:eks:NodeGroup [REDACTED]-eks-01-system delete original 
 -- aws:ec2:SecurityGroupRule [REDACTED]-eks-01-default-pod-secgrp-datadog-apm-ingress-8126 delete original 
 -- aws:ec2:SecurityGroupRule [REDACTED]-eks-01-default-pod-secgrp-linkerd-ingress-8090 delete original 
 -- aws:ec2:SecurityGroupRule [REDACTED]-eks-01-default-pod-secgrp-linkerd-ingress-8086 delete original 
 -- aws:ec2:SecurityGroupRule [REDACTED]-eks-01-default-pod-secgrp-linkerd-ingress-8080 delete original 
 -- aws:ec2:SecurityGroupRule [REDACTED]-eks-01-default-pod-secgrp-to-regular-pod delete original 
 -- aws:ec2:SecurityGroupRule [REDACTED]-eks-01-default-pod-secgrp-dns-ingress delete original 
 -- aws:eks:NodeGroup [REDACTED]-eks-01-internal-apps delete original 
 -- aws:iam:RolePolicyAttachment [REDACTED]-eks-01-policy-attach-vpc-resource-controller delete original 
 -- kubernetes:core/v1:ConfigMap [REDACTED]-eks-01-nodeAccess delete original 
 +- kubernetes:core/v1:ConfigMap [REDACTED]-eks-01-nodeAccess replace [diff: ~data]
 ++ kubernetes:core/v1:ConfigMap [REDACTED]-eks-01-nodeAccess create replacement [diff: ~data]
    aws:ec2:SecurityGroupRule [REDACTED]-eks-01-eksExtApiServerClusterIngressRule  [diff: ~provider]
    eks:index:VpcCni [REDACTED]-eks-01-vpc-cni  
    aws:ec2:SecurityGroupRule [REDACTED]-eks-01-eksNodeInternetEgressRule  [diff: ~provider]
    aws:ec2:SecurityGroupRule [REDACTED]-eks-01-eksNodeClusterIngressRule  [diff: ~provider]
    aws:ec2:SecurityGroupRule [REDACTED]-eks-01-eksClusterIngressRule  [diff: ~provider]
    aws:ec2:SecurityGroupRule [REDACTED]-eks-01-eksNodeIngressRule  [diff: ~provider]
    aws:iam:OpenIdConnectProvider [REDACTED]-eks-01-oidcProvider  [diff: ~provider]
 +- aws:iam:RolePolicyAttachment [REDACTED]-eks-01-policy-attach-vpc-resource-controller replace 
 ++ aws:iam:RolePolicyAttachment [REDACTED]-eks-01-policy-attach-vpc-resource-controller create replacement 
```

**Comment by thomas11** [comment]
Thanks, @Sefiris. We'll investigate.

**Comment by Sefiris** [comment]
To provide a small update on this.

We have found a way around this by disabling the previews and just full YOLO'ing the update. From what we could find with our googling this problem only occurred during previews(although these were very vague posts). I still think this is an issue as it makes me lose trust in the `pulumi preview` command.

The reason for this is the time sensitive upgrade to `1.22` as AWS EKS is deprecating `1.21` Feb 15th, so the choice for us to upgrade our alpha and staging clusters this way seemed appropriate, we have them for a reason anyways.

This upgrade succeeded without issues on 3 clusters now already(as expected though since i can't imagine this issue being on the AWS API side of things), the same issue with previews exists in `1.22` -> `1.23` as well, so i expect to have to do the same trick during that upgrade.

**Comment by iwahbe** [comment]
Hey @Sefiris. I have investigated briefly, and am able to repro. This program does it for me:

`__main__.py`:
```python
import pulumi_eks as eks

cluster_name = "my-cluster"
cluster_version = "1.21" # Switch to 1.22 for updating

cluster = eks.Cluster(
    f"{cluster_name}",
    eks.ClusterArgs(
        name=f"{cluster_name}",
        skip_default_node_group=True,
        node_associate_public_ip_address=False,
        version=cluster_version,
    ),
)
```

`requirements.txt.`
```
pulumi>=3.0.0,<4.0.0
pulumi-aws>=5.27.0
pulumi-eks>=0.42.2
```

I'm going to be looking into this later today.
